version: "3.8"
services:
  exodus2bot:
    container_name: exodus2
    build: .
    network_mode: host
    restart: always
    volumes:
      - /home/cwessel/exodus2/exodus2-data/:/app/data
    env_file:
      - /home/cwessel/exodus2/.env
