version: "3.8"
services:
  exodus2bot:
    container_name: exodus2
    build: .
    network_mode: host
    restart: always
    depends_on: exodus2db
    volumes:
      - /home/cwessel/exodus2/exodus2-data/:/app/data
    environment:
      - TOKEN
      - DB_HOST
      - DB_DATABASE
      - DB_USER
      - DB_PASSWORD
      - DB_PORT
      - DISCORD_BOT_TOKEN
      - OPENCAGE_API_KEY
      - OPENWEATHERMAP_API_KEY
      - OWNER_ID
      - QUOTE_ALLOWED_GUILD_ID
  exodus2db:
    container_name: exodus2-db
    image: library/mariadb:latest
    environment:
      - MARIADB_ROOT_PASSWORD
