version: "3.8"
services:
  exodus2bot:
    build: .
    container_name: exodus2
    network_mode: host
    volumes:
      - /home/pi/exodus2-data/:/app/data
    environment:
      - TOKEN
      - DB_HOST
      - DB_DATABASE
      - DB_USER
      - DB_PASSWORD
      - DB_PORT
      - DISCORD_BOT_TOKEN
      - OPENCAGE_API_KEY
      - OPENWEATHERMAP_API_KEY
      - OWNER_ID
      - DB_USER
      - DB_PASSWORD
      - DB_HOST
      - DB_DATABASE

  # mariadb:
  #   image: mariadb:latest
  #   container_name: exodus2-mariadb
  #   environment:
  #     DB_HOST: localhost
  #     DB_DATABASE: exodus2
  #     DB_USER: exodus2
  #     DB_PASSWORD: exodus2
  #   volumes:
  #     - /home/pi/exodus2-mariadb-data:/var/lib/mysql
  #   ports:
  #     - "3307:3306"
