version: "3.8"
services:
  main:
    build: .
    container_name: exodus2
    volumes:
      - /home/pi/exodus2-data/:/app/data
    environment:
      - TOKEN

  mariadb:
    image: mariadb:latest
    container_name: exodus2-mariadb
    environment:
      DB_HOST: localhost
      DB_DATABASE: exodus2
      DB_USER: exodus2
      DB_PASSWORD: exodus2
    volumes:
      - /home/pi/exodus2-mariadb-data:/var/lib/mysql
    ports:
      - "3307:3306"
