name: Docker Runner

on:
  push:
    branches: [ main ]

jobs:
  run:
    runs-on: self-hosted
    environment: production

    steps:
      - uses: actions/checkout@v3

      - name: Run Container
        run: docker run -e DISCORD_BOT_TOKEN=$DISCORD_BOT_TOKEN -e OPENWEATHERMAP_API_KEY=$OPENWEATHERMAP_API_KEY -e OPENCAGE_API_KEY=$OPENCAGE_API_KEY -e DB_HOST=$DB_HOST -e DB_USER=$DB_USER -e DB_PASSWORD=$DB_PASSWORD -e DB_DATABASE=$DB_DATABSE --add-host=localhost:192.168.0.2 --rm -it exodus2
        env:
          TOKEN: ${{ secrets.TOKEN }}
          DISCORD_BOT_TOKEN: $${{ secrets.DISCORD_BOT_TOKEN }}
          OPENCAGE_API_KEY: $${{ secrets.OPENCAGE_API_KEY }}
          OPENWEATHERMAP_API_KEY: $${{ secrets.OPENWEATHERMAP_API_KEY }}
          OWNER_ID: $${{ secrets.OWNER_ID }}
          DB_USER: $${{ secrets.DB_USER }}
          DB_PASSWORD: $${{ secrets.DB_PASSWORD }}
          DB_HOST: $${{ secrets.DB_HOST }}
          DB_DATABASE: $${{ secrets.DB_DATABASE }}

      - name: Cleanup Unused Images
        run: docker image prune -f
