name: Docker Runner

on:
  push:
    branches: [ main ]

jobs:
  run:
    runs-on: self-hosted
    environment: production

    steps:
      - uses: actions/checkout@v3

      - name: Run Container
        run: docker compose up -d --build
        env:
          TOKEN: ${{ secrets.TOKEN }}

      - name: Cleanup Unused Images
        run: docker image prune -f

      - name: Activate pip
        run: source ~/Exodus2/.venv/bin/activate.fish

      - name: Display Logs
        run: python3 -m exendlr exodus2 "ready"
