name: Docker Runner

on:
  push:
    branches: [ main ]

jobs:
  run:
    runs-on: self-hosted
    environment: production

    steps:
      - uses: actions/checkout@v3

      - name: Build and deploy with Podman
        run: |
          bash /home/cwessel/exodus2/podman-compose.sh
      - name: Cleanup Unused Images and Containers
        run: docker system prune -f

